// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vndzexrgryqmbbrqjjov.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZuZHpleHJncnlxbWJicnFqam92Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4MzA4MjksImV4cCI6MjA2NTQwNjgyOX0.vHKSdhaskDFJO5ajbBG5vKvA3DX0t3YiToYHN6RExAs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);